name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Check Docker Username
        run: |
          if [ -z "${{ vars.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME is not set!"
            exit 1
          else
            echo "DOCKER_USERNAME is set."
          fi
 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}  # 使用 env 上下文
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest  # 使用 env 上下文

     